# Site Settings
title: Robot Test Generation
tagline: Robot Test Generation
email: ch6wdf@virginia.edu
description: >
  A website describing the artifact for the paper: Feasible and Stressful Trajectory Generation for Mobile Robots
baseurl: "/robot-test-generation"
url: "TODO"
permalink: pretty
#favicon: /path/to/favicon.png
gh_sponsor: paper
theme: bulma-clean-theme

paginate: 3
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  shortname: robottestgen


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false